# Generated by Django 6.0.4 on 2026-04-26 20:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('infraestructura', '0001_initial'),
        ('ubicaciones', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoActuador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Tipo de actuador',
                'verbose_name_plural': 'Tipos de actuador',
                'db_table': 'tipos_actuador',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='TipoDispositivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Tipo de dispositivo',
                'verbose_name_plural': 'Tipos de dispositivo',
                'db_table': 'tipos_dispositivo',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='TipoSensor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
                ('variable_medida', models.CharField(max_length=50)),
                ('unidad_base', models.CharField(max_length=30)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Tipo de sensor',
                'verbose_name_plural': 'Tipos de sensor',
                'db_table': 'tipos_sensor',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Dispositivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('identificador_local', models.CharField(blank=True, max_length=100, null=True)),
                ('ip_local', models.GenericIPAddressField(blank=True, null=True)),
                ('version_firmware', models.CharField(blank=True, max_length=50, null=True)),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('inactivo', 'Inactivo'), ('falla', 'Falla'), ('mantenimiento', 'Mantenimiento')], default='activo', max_length=20)),
                ('ultima_conexion', models.DateTimeField(blank=True, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('fuente_agua', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dispositivos', to='infraestructura.fuenteagua')),
                ('ubicacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dispositivos', to='ubicaciones.ubicacion')),
                ('tipo_dispositivo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dispositivos', to='dispositivos.tipodispositivo')),
            ],
            options={
                'verbose_name': 'Dispositivo',
                'verbose_name_plural': 'Dispositivos',
                'db_table': 'dispositivos',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Actuador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('inactivo', 'Inactivo'), ('falla', 'Falla'), ('mantenimiento', 'Mantenimiento')], default='activo', max_length=20)),
                ('fecha_instalacion', models.DateField(blank=True, null=True)),
                ('invernadero', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actuadores', to='infraestructura.invernadero')),
                ('dispositivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actuadores', to='dispositivos.dispositivo')),
                ('tipo_actuador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='actuadores', to='dispositivos.tipoactuador')),
            ],
            options={
                'verbose_name': 'Actuador',
                'verbose_name_plural': 'Actuadores',
                'db_table': 'actuadores',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('modelo', models.CharField(blank=True, max_length=50, null=True)),
                ('numero_serie', models.CharField(blank=True, max_length=100, null=True)),
                ('precision_valor', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('inactivo', 'Inactivo'), ('falla', 'Falla'), ('mantenimiento', 'Mantenimiento')], default='activo', max_length=20)),
                ('fecha_instalacion', models.DateField(blank=True, null=True)),
                ('dispositivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sensores', to='dispositivos.dispositivo')),
                ('tipo_sensor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sensores', to='dispositivos.tiposensor')),
            ],
            options={
                'verbose_name': 'Sensor',
                'verbose_name_plural': 'Sensores',
                'db_table': 'sensores',
                'ordering': ['id'],
            },
        ),
    ]
