# Generated by Django 6.0.4 on 2026-04-26 21:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditoriaAccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accion', models.CharField(max_length=100)),
                ('entidad_afectada', models.CharField(max_length=100)),
                ('entidad_id', models.BigIntegerField(blank=True, null=True)),
                ('detalle', models.JSONField(blank=True, null=True)),
                ('ip_origen', models.GenericIPAddressField(blank=True, null=True)),
                ('fecha_accion', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auditoria_acciones', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Acción de auditoría',
                'verbose_name_plural': 'Acciones de auditoría',
                'db_table': 'auditoria_acciones',
                'ordering': ['-fecha_accion', '-id'],
                'indexes': [models.Index(fields=['entidad_afectada', '-fecha_accion'], name='idx_aud_ent_fecha'), models.Index(fields=['usuario', '-fecha_accion'], name='idx_aud_usr_fecha')],
            },
        ),
    ]
