# Generated by Django 6.0.4 on 2026-04-26 21:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dispositivos', '0001_initial'),
        ('infraestructura', '0001_initial'),
        ('ml', '0001_initial'),
        ('riego', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Alerta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_alerta', models.CharField(max_length=50)),
                ('severidad', models.CharField(choices=[('info', 'Info'), ('advertencia', 'Advertencia'), ('alta', 'Alta'), ('critica', 'Crítica')], max_length=20)),
                ('origen_alerta', models.CharField(choices=[('ml1', 'ML1'), ('ml2', 'ML2'), ('ml3', 'ML3'), ('sensor', 'Sensor'), ('mcp', 'MCP'), ('dashboard', 'Dashboard')], max_length=30)),
                ('mensaje', models.TextField()),
                ('estado_alerta', models.CharField(choices=[('activa', 'Activa'), ('reconocida', 'Reconocida'), ('resuelta', 'Resuelta')], default='activa', max_length=20)),
                ('fecha_generacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_reconocimiento', models.DateTimeField(blank=True, null=True)),
                ('decision_riego', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alertas', to='riego.decisionriego')),
                ('dispositivo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alertas', to='dispositivos.dispositivo')),
                ('invernadero', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alertas', to='infraestructura.invernadero')),
                ('sensor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alertas', to='dispositivos.sensor')),
                ('simulacion_ml3', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alertas', to='ml.simulacionml3')),
                ('usuario_reconoce', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alertas_reconocidas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Alerta',
                'verbose_name_plural': 'Alertas',
                'db_table': 'alertas',
                'ordering': ['-fecha_generacion', '-id'],
            },
        ),
        migrations.CreateModel(
            name='NotificacionLocal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_notificacion', models.CharField(choices=[('led', 'LED'), ('buzzer', 'Buzzer'), ('pantalla', 'Pantalla'), ('audio', 'Audio')], max_length=30)),
                ('estado_envio', models.CharField(choices=[('pendiente', 'Pendiente'), ('enviado', 'Enviado'), ('confirmado', 'Confirmado'), ('fallido', 'Fallido')], default='pendiente', max_length=20)),
                ('fecha_envio', models.DateTimeField(blank=True, null=True)),
                ('fecha_confirmacion', models.DateTimeField(blank=True, null=True)),
                ('detalle_respuesta', models.TextField(blank=True, null=True)),
                ('alerta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones_locales', to='alertas.alerta')),
            ],
            options={
                'verbose_name': 'Notificación local',
                'verbose_name_plural': 'Notificaciones locales',
                'db_table': 'notificaciones_locales',
                'ordering': ['-id'],
            },
        ),
        migrations.AddIndex(
            model_name='alerta',
            index=models.Index(fields=['estado_alerta', '-fecha_generacion'], name='idx_alertas_est_fecha'),
        ),
    ]
