# Generated by Django 6.0.4 on 2026-04-26 21:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReporteSemanal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periodo_inicio', models.DateField()),
                ('periodo_fin', models.DateField()),
                ('volumen_captado_l', models.DecimalField(decimal_places=4, default=0, max_digits=14)),
                ('volumen_predicho_l', models.DecimalField(decimal_places=4, default=0, max_digits=14)),
                ('eficiencia_riego', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('total_alertas', models.IntegerField(default=0)),
                ('resumen', models.TextField(blank=True, null=True)),
                ('fecha_generacion', models.DateTimeField(auto_now_add=True)),
                ('generado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reportes_generados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Reporte semanal',
                'verbose_name_plural': 'Reportes semanales',
                'db_table': 'reportes_semanales',
                'ordering': ['-periodo_fin', '-id'],
                'constraints': [models.CheckConstraint(condition=models.Q(('periodo_fin__gte', models.F('periodo_inicio'))), name='chk_periodo_reporte')],
            },
        ),
    ]
