from app.models.user import User
from app.models.perfil import Perfil
from app.models.catalogos import *
from app.models.seguridad import *
from app.models.infraestructura import *
from app.models.dispositivos import *
from app.models.ml import *
from app.models.riego import *
from app.models.alertas import *
from app.models.umbrales import *
from app.models.reportes import *
from app.models.solicitudes import *
from app.models.tickets_mantenimiento import *