networks:
  backend-net:
    driver: bridge

volumes:
  postgres_data:
  api_uploads:

services:
  # Base de Datos Aislada
  db-atina:
    image: postgres:15-alpine
    container_name: atina_postgres_prod
    restart: always
    environment:
      # Postgres usa estas variables nativas para inicializarse
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - backend-net

  # Backend FastAPI
  backend-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: atina_backend_prod
    restart: always
    environment:
      # Pasamos las credenciales que Pydantic necesita
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      SECRET_KEY: ${SECRET_KEY}
      
      # CAMBIO CRUCIAL: Le decimos a Pydantic que busque el contenedor de la BD, no localhost
      POSTGRES_SERVER: db-atina
      POSTGRES_PORT: 5432
      
      # Configuraciones de producción obligatorias
      APP_ENV: production
      DEBUG: "False"
    volumes:
      - api_uploads:/workspace/uploads
    depends_on:
      - db-atina
    networks:
      - backend-net
    ports:
      - "8000:8000"
