# Generated by Django 6.0.4 on 2026-04-26 21:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dispositivos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LecturaSensor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=4, max_digits=14)),
                ('calidad_dato', models.CharField(choices=[('valido', 'Válido'), ('estimado', 'Estimado'), ('atipico', 'Atípico'), ('invalido', 'Inválido')], default='valido', max_length=20)),
                ('timestamp_lectura', models.DateTimeField()),
                ('timestamp_recepcion', models.DateTimeField(auto_now_add=True)),
                ('metadatos', models.JSONField(blank=True, null=True)),
                ('sensor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lecturas', to='dispositivos.sensor')),
            ],
            options={
                'verbose_name': 'Lectura de sensor',
                'verbose_name_plural': 'Lecturas de sensores',
                'db_table': 'lecturas_sensor',
                'ordering': ['-timestamp_lectura'],
                'indexes': [models.Index(fields=['sensor', '-timestamp_lectura'], name='idx_lecturas_sensor_sensor_fecha')],
            },
        ),
    ]
