# Generated by Django 6.0.4 on 2026-04-26 21:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monitoreo', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='lecturasensor',
            new_name='idx_lecturas_sensor_sens_fecha',
            old_name='idx_lecturas_sensor_sensor_fecha',
        ),
    ]
