# Generated by Django 6.0.4 on 2026-04-26 21:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dispositivos', '0001_initial'),
        ('infraestructura', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionUmbral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_parametro', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('valor', models.DecimalField(decimal_places=4, max_digits=14)),
                ('unidad', models.CharField(blank=True, max_length=30, null=True)),
                ('ambito', models.CharField(choices=[('global', 'Global'), ('invernadero', 'Invernadero'), ('sensor', 'Sensor')], default='global', max_length=30)),
                ('editable', models.BooleanField(default=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('actualizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='umbrales_actualizados', to=settings.AUTH_USER_MODEL)),
                ('invernadero', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='configuraciones_umbral', to='infraestructura.invernadero')),
                ('sensor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='configuraciones_umbral', to='dispositivos.sensor')),
            ],
            options={
                'verbose_name': 'Configuración de umbral',
                'verbose_name_plural': 'Configuraciones de umbral',
                'db_table': 'configuraciones_umbral',
                'ordering': ['nombre_parametro', 'id'],
                'constraints': [models.CheckConstraint(condition=models.Q(('ambito__in', ['global', 'invernadero', 'sensor'])), name='chk_umbral_ambito_val'), models.CheckConstraint(condition=models.Q(models.Q(('ambito', 'global'), ('invernadero__isnull', True), ('sensor__isnull', True)), models.Q(('ambito', 'invernadero'), ('invernadero__isnull', False), ('sensor__isnull', True)), models.Q(('ambito', 'sensor'), ('sensor__isnull', False)), _connector='OR'), name='chk_umbral_scope_cfg')],
            },
        ),
    ]
