# Generated by Django 6.0.4 on 2026-04-26 21:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dispositivos', '0001_initial'),
        ('infraestructura', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DecisionRiego',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origen_decision', models.CharField(choices=[('ml2', 'ML2'), ('manual', 'Manual'), ('regla_seguridad', 'Regla de seguridad'), ('tecnico', 'Técnico'), ('docente', 'Docente')], max_length=30)),
                ('modo_riego', models.CharField(choices=[('automatico', 'Automático'), ('manual', 'Manual'), ('contingencia', 'Contingencia')], max_length=20)),
                ('estado_valvula', models.CharField(choices=[('abierta', 'Abierta'), ('cerrada', 'Cerrada'), ('parcial', 'Parcial'), ('falla', 'Falla')], max_length=20)),
                ('volumen_disponible_l', models.DecimalField(decimal_places=4, default=0, max_digits=14)),
                ('demanda_estimada_l', models.DecimalField(decimal_places=4, default=0, max_digits=14)),
                ('volumen_aplicado_l', models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True)),
                ('decision_texto', models.TextField(blank=True, null=True)),
                ('ejecutado_en', models.DateTimeField(auto_now_add=True)),
                ('actuador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='decisiones_riego', to='dispositivos.actuador')),
                ('fuente_agua', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='decisiones_riego', to='infraestructura.fuenteagua')),
                ('invernadero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='decisiones_riego', to='infraestructura.invernadero')),
            ],
            options={
                'verbose_name': 'Decisión de riego',
                'verbose_name_plural': 'Decisiones de riego',
                'db_table': 'decisiones_riego',
                'ordering': ['-ejecutado_en', '-id'],
            },
        ),
        migrations.CreateModel(
            name='EstadoRiegoActual',
            fields=[
                ('invernadero', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='estado_riego_actual', serialize=False, to='infraestructura.invernadero')),
                ('actualizado_en', models.DateTimeField(auto_now_add=True)),
                ('ultima_decision', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='estados_riego_actual', to='riego.decisionriego')),
            ],
            options={
                'verbose_name': 'Estado de riego actual',
                'verbose_name_plural': 'Estados de riego actual',
                'db_table': 'estado_riego_actual',
            },
        ),
        migrations.AddIndex(
            model_name='decisionriego',
            index=models.Index(fields=['invernadero', '-ejecutado_en'], name='idx_dec_riego_inv_fecha'),
        ),
    ]
