# Generated by Django 6.0.4 on 2026-04-26 21:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dispositivos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CalibracionSensor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_calibracion', models.CharField(max_length=50)),
                ('valor_anterior', models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True)),
                ('valor_nuevo', models.DecimalField(decimal_places=4, max_digits=14)),
                ('motivo', models.TextField(blank=True, null=True)),
                ('fecha_calibracion', models.DateTimeField(auto_now_add=True)),
                ('sensor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calibraciones', to='dispositivos.sensor')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='calibraciones_sensor', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Calibración de sensor',
                'verbose_name_plural': 'Calibraciones de sensores',
                'db_table': 'calibraciones_sensor',
                'ordering': ['-fecha_calibracion', '-id'],
            },
        ),
    ]
