"""remove_unique_constraint_ubicacion_atrapanieblas

Revision ID: 3099b8b58fec
Revises: 157615975f4d
Create Date: 2026-05-27 15:45:43.441672

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3099b8b58fec'
down_revision: Union[str, Sequence[str], None] = '157615975f4d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('atrapanieblas_ubicacion_id_key', 'atrapanieblas', type_='unique')
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('atrapanieblas_ubicacion_id_key', 'atrapanieblas', ['ubicacion_id'])
    # ### end Alembic commands ###