"""add 2fa fields

Revision ID: 400d475bfb78
Revises: 83e0c67048fa
Create Date: 2026-05-05 20:25:29.851423

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '400d475bfb78'
down_revision: Union[str, Sequence[str], None] = '83e0c67048fa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('idx_decisiones_riego_ejecutado_en'), table_name='decisiones_riego')
    op.drop_index(op.f('idx_eventos_riego_decision_id'), table_name='eventos_riego')
    op.drop_constraint(op.f('uq_fuentes_agua_atrapanieblas'), 'fuentes_agua_atrapanieblas', type_='unique')
    op.drop_index(op.f('idx_lecturas_sensor_sensor_fecha'), table_name='lecturas_sensor')
    op.drop_index(op.f('idx_predicciones_ml_fuente_fecha'), table_name='predicciones_ml')
    op.drop_index(op.f('idx_simulaciones_ml_invernadero_fecha'), table_name='simulaciones_ml')
    op.add_column('users', sa.Column('totp_secret', sa.String(length=32), nullable=True))
    op.add_column('users', sa.Column('is_totp_enabled', sa.Boolean(), nullable=False))
    op.add_column('users', sa.Column('is_email_2fa_enabled', sa.Boolean(), nullable=False))
    op.add_column('users', sa.Column('email_code', sa.String(length=6), nullable=True))
    op.add_column('users', sa.Column('email_code_expires', sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_column('users', 'email_code_expires')
    op.drop_column('users', 'email_code')
    op.drop_column('users', 'is_email_2fa_enabled')
    op.drop_column('users', 'is_totp_enabled')
    op.drop_column('users', 'totp_secret')
    op.create_index(op.f('idx_simulaciones_ml_invernadero_fecha'), 'simulaciones_ml', ['invernadero_id', sa.literal_column('fecha_generacion DESC')], unique=False)
    op.create_index(op.f('idx_predicciones_ml_fuente_fecha'), 'predicciones_ml', ['fuente_agua_id', sa.literal_column('fecha_objetivo DESC')], unique=False)
    op.create_index(op.f('idx_lecturas_sensor_sensor_fecha'), 'lecturas_sensor', ['sensor_id', sa.literal_column('timestamp_lectura DESC')], unique=False)
    op.create_unique_constraint(op.f('uq_fuentes_agua_atrapanieblas'), 'fuentes_agua_atrapanieblas', ['fuente_agua_id', 'atrapaniebla_id'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('idx_eventos_riego_decision_id'), 'eventos_riego', ['decision_riego_id'], unique=False)
    op.create_index(op.f('idx_decisiones_riego_ejecutado_en'), 'decisiones_riego', [sa.literal_column('ejecutado_en DESC')], unique=False)
    # ### end Alembic commands ###
