"""Se agregó catalogos e infraestructura

Revision ID: a2f0088855d4
Revises: 353e9b33db40
Create Date: 2026-05-05 18:29:22.137939

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = 'a2f0088855d4'
down_revision: Union[str, Sequence[str], None] = '353e9b33db40'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('estados_atrapaniebla',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=30), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre')
    )
    op.create_table('estados_fuente_agua',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=30), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre')
    )
    op.create_table('estados_invernadero',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=30), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre')
    )
    op.create_table('tipos_fuente_agua',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=30), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre')
    )
    op.create_table('tipos_ubicacion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=30), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre')
    )
    op.create_table('auditoria_acciones',
    sa.Column('id', sa.Integer(), nullable=False),
    # CAMBIO: usuario_id a usuario_ci
    sa.Column('usuario_ci', sa.String(length=20), nullable=True),
    sa.Column('accion', sa.String(length=100), nullable=False),
    sa.Column('entidad_afectada', sa.String(length=100), nullable=False),
    sa.Column('entidad_id', sa.Integer(), nullable=True),
    sa.Column('detalle_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('ip_origen', postgresql.INET(), nullable=True),
    sa.Column('fecha_accion', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    # CAMBIO: Apunta a users.ci en lugar de users.id
    sa.ForeignKeyConstraint(['usuario_ci'], ['users.ci'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    # CAMBIO: Actualización del nombre de índice
    op.create_index(op.f('ix_auditoria_acciones_usuario_ci'), 'auditoria_acciones', ['usuario_ci'], unique=False)
    
    op.create_table('ubicaciones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tipo_ubicacion_id', sa.Integer(), nullable=False),
    sa.Column('ubicacion_padre_id', sa.Integer(), nullable=True),
    sa.Column('nombre', sa.String(length=120), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('latitud', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('longitud', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('altitud_m', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['tipo_ubicacion_id'], ['tipos_ubicacion.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['ubicacion_padre_id'], ['ubicaciones.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ubicaciones_tipo_ubicacion_id'), 'ubicaciones', ['tipo_ubicacion_id'], unique=False)
    op.create_index(op.f('ix_ubicaciones_ubicacion_padre_id'), 'ubicaciones', ['ubicacion_padre_id'], unique=False)
    op.create_table('atrapanieblas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ubicacion_id', sa.Integer(), nullable=False),
    sa.Column('codigo', sa.String(length=30), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('area_malla_m2', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('tipo_malla', sa.String(length=50), nullable=True),
    sa.Column('orientacion', sa.String(length=30), nullable=True),
    sa.Column('estado_atrapaniebla_id', sa.Integer(), nullable=False),
    sa.Column('fecha_instalacion', sa.DateTime(timezone=True), nullable=True),
    sa.Column('creado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['estado_atrapaniebla_id'], ['estados_atrapaniebla.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['ubicacion_id'], ['ubicaciones.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('codigo'),
    sa.UniqueConstraint('ubicacion_id')
    )
    op.create_index(op.f('ix_atrapanieblas_estado_atrapaniebla_id'), 'atrapanieblas', ['estado_atrapaniebla_id'], unique=False)
    op.create_table('fuentes_agua',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ubicacion_id', sa.Integer(), nullable=True),
    sa.Column('tipo_fuente_agua_id', sa.Integer(), nullable=False),
    sa.Column('codigo', sa.String(length=30), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('capacidad_l', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('estado_fuente_agua_id', sa.Integer(), nullable=False),
    sa.Column('creado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['estado_fuente_agua_id'], ['estados_fuente_agua.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['tipo_fuente_agua_id'], ['tipos_fuente_agua.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['ubicacion_id'], ['ubicaciones.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('codigo')
    )
    op.create_index(op.f('ix_fuentes_agua_estado_fuente_agua_id'), 'fuentes_agua', ['estado_fuente_agua_id'], unique=False)
    op.create_table('invernaderos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ubicacion_id', sa.Integer(), nullable=False),
    sa.Column('codigo', sa.String(length=30), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('area_m2', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('prioridad_riego', sa.SmallInteger(), nullable=False),
    sa.Column('estado_invernadero_id', sa.Integer(), nullable=False),
    sa.Column('creado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['estado_invernadero_id'], ['estados_invernadero.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['ubicacion_id'], ['ubicaciones.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('codigo'),
    sa.UniqueConstraint('ubicacion_id')
    )
    op.create_index(op.f('ix_invernaderos_estado_invernadero_id'), 'invernaderos', ['estado_invernadero_id'], unique=False)
    op.create_table('fuentes_agua_atrapanieblas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fuente_agua_id', sa.Integer(), nullable=False),
    sa.Column('atrapaniebla_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['atrapaniebla_id'], ['atrapanieblas.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['fuente_agua_id'], ['fuentes_agua.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('fuente_agua_id', 'atrapaniebla_id', name='uq_fuentes_agua_atrapanieblas')
    )
    op.create_index(op.f('ix_fuentes_agua_atrapanieblas_atrapaniebla_id'), 'fuentes_agua_atrapanieblas', ['atrapaniebla_id'], unique=False)
    op.create_index(op.f('ix_fuentes_agua_atrapanieblas_fuente_agua_id'), 'fuentes_agua_atrapanieblas', ['fuente_agua_id'], unique=False)
    # ### end Alembic commands ###
    op.create_check_constraint(
    "chk_invernaderos_area",
    "invernaderos",
    "area_m2 > 0",
    )

    op.create_check_constraint(
        "chk_invernaderos_prioridad",
        "invernaderos",
        "prioridad_riego BETWEEN 1 AND 10",
    )

    op.create_check_constraint(
        "chk_atrapanieblas_area",
        "atrapanieblas",
        "area_malla_m2 > 0",
    )

    op.create_check_constraint(
        "chk_fuentes_agua_capacidad",
        "fuentes_agua",
        "capacidad_l IS NULL OR capacidad_l >= 0",
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("chk_fuentes_agua_capacidad", "fuentes_agua", type_="check")
    op.drop_constraint("chk_atrapanieblas_area", "atrapanieblas", type_="check")
    op.drop_constraint("chk_invernaderos_prioridad", "invernaderos", type_="check")
    op.drop_constraint("chk_invernaderos_area", "invernaderos", type_="check")
    op.drop_index(op.f('ix_fuentes_agua_atrapanieblas_fuente_agua_id'), table_name='fuentes_agua_atrapanieblas')
    op.drop_index(op.f('ix_fuentes_agua_atrapanieblas_atrapaniebla_id'), table_name='fuentes_agua_atrapanieblas')
    op.drop_table('fuentes_agua_atrapanieblas')
    op.drop_index(op.f('ix_invernaderos_estado_invernadero_id'), table_name='invernaderos')
    op.drop_table('invernaderos')
    op.drop_index(op.f('ix_fuentes_agua_estado_fuente_agua_id'), table_name='fuentes_agua')
    op.drop_table('fuentes_agua')
    op.drop_index(op.f('ix_atrapanieblas_estado_atrapaniebla_id'), table_name='atrapanieblas')
    op.drop_table('atrapanieblas')
    op.drop_index(op.f('ix_ubicaciones_ubicacion_padre_id'), table_name='ubicaciones')
    op.drop_index(op.f('ix_ubicaciones_tipo_ubicacion_id'), table_name='ubicaciones')
    op.drop_table('ubicaciones')
    # CAMBIO: Actualización del nombre de índice para el downgrade
    op.drop_index(op.f('ix_auditoria_acciones_usuario_ci'), table_name='auditoria_acciones')
    op.drop_table('auditoria_acciones')
    op.drop_table('tipos_ubicacion')
    op.drop_table('tipos_fuente_agua')
    op.drop_table('estados_invernadero')
    op.drop_table('estados_fuente_agua')
    op.drop_table('estados_atrapaniebla')
    # ### end Alembic commands ###