# Generated by Django 6.0.4 on 2026-04-26 20:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ubicaciones', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Atrapaniebla',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=30, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('area_malla_m2', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tipo_malla', models.CharField(blank=True, max_length=50, null=True)),
                ('orientacion', models.CharField(blank=True, max_length=30, null=True)),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('inactivo', 'Inactivo'), ('mantenimiento', 'Mantenimiento')], default='activo', max_length=20)),
                ('fecha_instalacion', models.DateField(blank=True, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('ubicacion', models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, related_name='atrapaniebla', to='ubicaciones.ubicacion')),
            ],
            options={
                'verbose_name': 'Atrapaniebla',
                'verbose_name_plural': 'Atrapanieblas',
                'db_table': 'atrapanieblas',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='FuenteAgua',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=30, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('tipo_fuente', models.CharField(choices=[('atrapaniebla', 'Atrapaniebla'), ('manantial', 'Manantial'), ('tanque', 'Tanque'), ('otro', 'Otro')], max_length=30)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('capacidad_l', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('inactivo', 'Inactivo'), ('mantenimiento', 'Mantenimiento')], default='activo', max_length=20)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('ubicacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fuentes_agua', to='ubicaciones.ubicacion')),
            ],
            options={
                'verbose_name': 'Fuente de agua',
                'verbose_name_plural': 'Fuentes de agua',
                'db_table': 'fuentes_agua',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Invernadero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=30, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('area_m2', models.DecimalField(decimal_places=2, max_digits=10)),
                ('prioridad_riego', models.PositiveSmallIntegerField(default=1)),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('inactivo', 'Inactivo'), ('mantenimiento', 'Mantenimiento')], default='activo', max_length=20)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('ubicacion', models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, related_name='invernadero', to='ubicaciones.ubicacion')),
            ],
            options={
                'verbose_name': 'Invernadero',
                'verbose_name_plural': 'Invernaderos',
                'db_table': 'invernaderos',
                'ordering': ['id'],
            },
        ),
    ]
