# Generated by Django 6.0.4 on 2026-04-26 22:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PerfilUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ci_documento', models.CharField(max_length=30, unique=True)),
                ('telefono', models.CharField(blank=True, max_length=20)),
                ('direccion', models.CharField(blank=True, max_length=255)),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('genero', models.CharField(blank=True, choices=[('masculino', 'Masculino'), ('femenino', 'Femenino'), ('otro', 'Otro'), ('no_decir', 'Prefiero no decir')], max_length=20)),
                ('fotografia', models.ImageField(blank=True, null=True, upload_to='perfiles/')),
                ('cargo_descripcion', models.CharField(blank=True, max_length=150)),
                ('relacion_sistema', models.CharField(choices=[('admin', 'Administrador'), ('docente', 'Docente'), ('tecnico', 'Técnico'), ('estudiante', 'Estudiante'), ('otro', 'Otro')], default='otro', max_length=20)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
