# Generated by Django 6.0.4 on 2026-04-26 20:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ubicacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120)),
                ('tipo_ubicacion', models.CharField(choices=[('campus', 'Campus'), ('sector', 'Sector'), ('invernadero', 'Invernadero'), ('atrapaniebla', 'Atrapaniebla'), ('laboratorio', 'Laboratorio'), ('fuente_agua', 'Fuente de agua')], max_length=30)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('latitud', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitud', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('altitud_m', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sububicaciones', to='ubicaciones.ubicacion')),
            ],
            options={
                'verbose_name': 'Ubicación',
                'verbose_name_plural': 'Ubicaciones',
                'db_table': 'ubicaciones',
                'ordering': ['id'],
            },
        ),
    ]
