@startuml

left to right direction
skinparam shadowing false
skinparam packageStyle rectangle

actor Administrador
actor Docente

rectangle "Sistema Inteligente de Optimización, Recolección y Predicción de Agua" {

    usecase "Autenticarse" as UC_Login

    usecase "Validar\nCredenciales" as UC_Validar
    usecase "Generar\nSesión" as UC_Sesion
    usecase "Registrar\nAcceso" as UC_Registro

    UC_Login .> UC_Validar : <<include>>
    UC_Login .> UC_Sesion : <<include>>
    UC_Login .> UC_Registro : <<include>>

}

Administrador --> UC_Login
Docente --> UC_Login

@enduml