# Generated by Django 6.0.4 on 2026-04-26 21:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dispositivos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SincronizacionMCP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origen', models.CharField(max_length=50)),
                ('destino', models.CharField(max_length=50)),
                ('tipo_recurso', models.CharField(max_length=50)),
                ('estado_sincronizacion', models.CharField(choices=[('exito', 'Éxito'), ('parcial', 'Parcial'), ('fallo', 'Fallo'), ('en_proceso', 'En proceso')], max_length=20)),
                ('cantidad_registros', models.IntegerField(default=0)),
                ('fecha_inicio', models.DateTimeField(auto_now_add=True)),
                ('fecha_fin', models.DateTimeField(blank=True, null=True)),
                ('mensaje_resultado', models.TextField(blank=True, null=True)),
                ('dispositivo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sincronizaciones_mcp', to='dispositivos.dispositivo')),
            ],
            options={
                'verbose_name': 'Sincronización MCP',
                'verbose_name_plural': 'Sincronizaciones MCP',
                'db_table': 'sincronizaciones_mcp',
                'ordering': ['-fecha_inicio', '-id'],
            },
        ),
    ]
