# Generated by Django 6.0.4 on 2026-04-26 21:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('infraestructura', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrediccionML1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_prediccion', models.DateField()),
                ('fecha_objetivo', models.DateField()),
                ('volumen_predicho_l', models.DecimalField(decimal_places=4, max_digits=14)),
                ('margen_error', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('confianza_modelo', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('variables_entrada_resumen', models.JSONField(blank=True, null=True)),
                ('version_modelo', models.CharField(max_length=50)),
                ('generado_en', models.DateTimeField(auto_now_add=True)),
                ('fuente_agua', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='predicciones_ml1', to='infraestructura.fuenteagua')),
            ],
            options={
                'verbose_name': 'Predicción ML1',
                'verbose_name_plural': 'Predicciones ML1',
                'db_table': 'predicciones_ml1',
                'ordering': ['-fecha_objetivo', '-id'],
                'constraints': [models.UniqueConstraint(fields=('fuente_agua', 'fecha_objetivo', 'version_modelo'), name='uq_pred_ml1_fuente_fecha_ver')],
            },
        ),
        migrations.CreateModel(
            name='SimulacionML3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_generacion', models.DateTimeField(auto_now_add=True)),
                ('horizonte_horas', models.IntegerField(default=72)),
                ('escenario', models.CharField(choices=[('riego_normal', 'Riego normal'), ('riego_restringido', 'Riego restringido'), ('sin_riego', 'Sin riego')], max_length=30)),
                ('nivel_riesgo', models.CharField(choices=[('bajo', 'Bajo'), ('medio', 'Medio'), ('alto', 'Alto'), ('critico', 'Crítico')], max_length=20)),
                ('descripcion_resultado', models.TextField(blank=True, null=True)),
                ('recomendacion', models.TextField(blank=True, null=True)),
                ('version_modelo', models.CharField(max_length=50)),
                ('generado_en', models.DateTimeField(auto_now_add=True)),
                ('invernadero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='simulaciones_ml3', to='infraestructura.invernadero')),
            ],
            options={
                'verbose_name': 'Simulación ML3',
                'verbose_name_plural': 'Simulaciones ML3',
                'db_table': 'simulaciones_ml3',
                'ordering': ['-fecha_generacion', '-id'],
                'indexes': [models.Index(fields=['invernadero', '-fecha_generacion'], name='idx_sim_ml3_inv_fecha')],
            },
        ),
    ]
